services:
  ollama:
    image: ollama/ollama:rocm
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - "105"
      - "39"
    container_name: ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=-1
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
    security_opt:
      - no-new-privileges:true
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    entrypoint: ["sh", "-c", "ollama serve & until ollama list >/dev/null 2>&1; do sleep 1; done; ollama pull llama3.2; ollama pull nomic-embed-text:latest; ollama pull qwen2.5:7b; ollama pull qwen3.5:9b; wait $!"]

volumes:
  ollama_data: