services:
  entropy-backend-ms-users:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: entropy_backend_ms_users
    ports:
      - '3008:3008' #Microservice port
      - '3009:3009' #MCP port
    volumes:
      - .:/app
